### ISSUE TITLE
Diagrama E-R

### ISSUE THREAD

**Issue by EvelynMC** [EvelynMC/SistemaERPWeb#14]
- 12 al 16 de Agosto

**Comment by EvelynMC** [comment]
Comenzaremos con bosquejos básicos que compararemos y discutiremos de aquí al 16 como máximo. Ojalá terminarlos el sábado 12 incluso, para validarlos con el profesor en sala.

Un saludito!

**Comment by EvelynMC** [comment]
Se comenzará sábado 12 de agosto con los diagramas preliminares, ya que se asignará en clase el siguiente módulo a trabajar.

Un saludito

**Comment by EvelynMC** [comment]
Se acaba de asignar el módulo nuevo para pasar a  la fase de diseño. Fue asignado el módulo de ventas, trabajo de Adolfo Correa y Jean Vásquez. Yo tengo el informe impreso. Hoy empezaremos en clases el desarrollo del diagrama de E-R de éste módulo.

**Comment by jcbustamantep** [comment]
Pidele el digital y me lo envias para trabajar desde la cama 😀

**Comment by EvelynMC** [comment]
Pedido
